[backdrop]
enabled = true

[bar.default]
background_opacity = 0.5
capsule = true
capsule_opaciy = 0.25
margin_ends = 0
radius = 0
radius_bottom_left = 12
radius_bottom_right = 12
scale = 1.3
start = [
   "workspaces",
   "taskbar"
]
center = [
    "clock",
    "weather",
    "media"
]
end = [
    "tray",
    "notifications",
    "clipboard",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "session"
]

[calendar]
enabled = true
refresh_minutes = 5

    [calendar.account.personal_google]
    type = "google"

[dock]
auto_hide = true
background_opacity = 0.2
enabled = true
launcher_position = "end"
pinned = [
    "firefox",
    "Alacritty"
]
reserve_space = false
show_dots = true

[shell]
date_format = "%Y-%m-%d, %A"
time_format = "%Y-%m-%d, %A"
launch_apps_as_systemd_servies = true
niri_overview_type_to_launch_enabled = true
polkit_agent = true

    [shell.launcher]
    session_search = true
    
    [shell.panel]
    control_center_placement = "floating"
    launcher_placement = 'attached'

[theme]
mode = dark
source = "wallpaper"

    [theme.templates]
    builtin_ids = [
        "alacritty",
        "gtk3",
        "gtk4",
        "kcolorscheme",
        "niri",
        "qt"
    ]
    community_ids = [
        "obs",
        "steam"
    ]

[wallpaper.default]
path = "~/.nixos/assets/wallpapers/Mostar.png"

[widget.clock]
format = "{:%Y-%m-%d, %H:%M:%S}"
scale = = 0.9

[widget.media]
album_art_only = true
hide_when_no_media = true

[widget.network]
show_label = false

[widget.taskbar]
inactive_opacity = 0.5
only_active_workspace = true

[widget.volume]
show_label = false

[widget.weather]
show_condition = false
show_temperature = false

widget.workspace]
display = "none"
